// Build step: bake the built SPA shell (dist/index.html) into api/_shell.mjs so
// the portal function can inject OG meta without fs access or self-fetching.
import fs from 'node:fs';

const shell = fs.readFileSync('dist/index.html', 'utf8');
const out = `// GENERATED by scripts/bake-shell.mjs — do not edit\nexport const SHELL_HTML = ${JSON.stringify(shell)};\n`;
fs.writeFileSync('api/_shell.mjs', out);
console.log('bake-shell: wrote api/_shell.mjs (' + out.length + ' bytes)');
